"""add resumable collections and schema profiles

Revision ID: 4aab642f84e7
Revises: dd596b496fe1
Create Date: 2026-07-29 23:27:41.301124
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4aab642f84e7"
down_revision: str | Sequence[str] | None = "dd596b496fe1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_collections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("query_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("query_definition", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_total", sa.Integer(), nullable=True),
        sa.Column("collected_total", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_ingestion_collections_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_collections")),
    )
    op.create_index(
        "ix_collection_source_query_status",
        "ingestion_collections",
        ["source_id", "query_fingerprint", "status"],
        unique=False,
    )
    op.create_table(
        "source_schema_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_type", sa.String(length=80), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("top_level_schema", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_source_schema_profiles_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_schema_profiles")),
        sa.UniqueConstraint(
            "source_id", "external_type", "fingerprint", name="source_schema_fingerprint"
        ),
    )
    op.create_index(
        "ix_schema_profile_source_type_seen",
        "source_schema_profiles",
        ["source_id", "external_type", "last_seen_at"],
        unique=False,
    )
    op.create_table(
        "collection_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("cursor_in", sa.JSON(), nullable=True),
        sa.Column("cursor_out", sa.JSON(), nullable=True),
        sa.Column("items_returned", sa.Integer(), nullable=False),
        sa.Column("is_last_page", sa.Boolean(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("expected_total", sa.Integer(), nullable=True),
        sa.Column("collected_total", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["ingestion_collections.id"],
            name=op.f("fk_collection_pages_collection_id_ingestion_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_collection_pages_run_id_ingestion_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_pages")),
        sa.UniqueConstraint("collection_id", "page_number", name="collection_page_number"),
    )
    op.create_table(
        "ingestion_checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("last_run_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("query_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("connector_version", sa.String(length=80), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=True),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["ingestion_collections.id"],
            name=op.f("fk_ingestion_checkpoints_collection_id_ingestion_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["last_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_ingestion_checkpoints_last_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_ingestion_checkpoints_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_checkpoints")),
        sa.UniqueConstraint(
            "source_id", "job_type", "query_fingerprint", name="ingestion_checkpoint_query"
        ),
    )
    op.add_column("ingestion_runs", sa.Column("collection_id", sa.Uuid(), nullable=True))
    op.add_column(
        "ingestion_runs", sa.Column("query_fingerprint", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_ingestion_runs_query_fingerprint"),
        "ingestion_runs",
        ["query_fingerprint"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_ingestion_runs_collection_id_ingestion_collections"),
        "ingestion_runs",
        "ingestion_collections",
        ["collection_id"],
        ["id"],
    )
    op.add_column("raw_snapshots", sa.Column("schema_hint", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_snapshots", "schema_hint")
    op.drop_constraint(
        op.f("fk_ingestion_runs_collection_id_ingestion_collections"),
        "ingestion_runs",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_ingestion_runs_query_fingerprint"), table_name="ingestion_runs")
    op.drop_column("ingestion_runs", "query_fingerprint")
    op.drop_column("ingestion_runs", "collection_id")
    op.drop_table("ingestion_checkpoints")
    op.drop_table("collection_pages")
    op.drop_index("ix_schema_profile_source_type_seen", table_name="source_schema_profiles")
    op.drop_table("source_schema_profiles")
    op.drop_index("ix_collection_source_query_status", table_name="ingestion_collections")
    op.drop_table("ingestion_collections")
    # ### end Alembic commands ###
