"""initial source ingestion schema

Revision ID: 9752c25a7b36
Revises:
Create Date: 2026-07-29 20:36:19.404115
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9752c25a7b36"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("policy_status", sa.String(length=30), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=True),
        sa.Column("commercial_use_status", sa.String(length=30), nullable=False),
        sa.Column("storage_permission", sa.String(length=30), nullable=False),
        sa.Column("derived_data_permission", sa.String(length=30), nullable=False),
        sa.Column("llm_processing_permission", sa.String(length=30), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("key", name=op.f("uq_data_sources_key")),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("canonical_url", sa.String(length=800), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_table(
        "entity_external_ids",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_type", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("external_url", sa.String(length=800), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_entity_external_ids_entity_id_entities")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_entity_external_ids_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_external_ids")),
        sa.UniqueConstraint("source_id", "external_type", "external_id", name="external_id"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("connector_version", sa.String(length=80), nullable=False),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("query_definition", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("checkpoint_before", sa.JSON(), nullable=True),
        sa.Column("checkpoint_after", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("raw_item_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_ingestion_runs_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("registry", sa.String(length=50), nullable=False),
        sa.Column("package_name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("license_expression", sa.String(length=300), nullable=True),
        sa.Column("repository_url_raw", sa.String(length=800), nullable=True),
        sa.Column("homepage_url", sa.String(length=800), nullable=True),
        sa.Column("created_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["entities.id"], name=op.f("fk_packages_id_entities")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("registry", "package_name", name="registry_package"),
    )
    op.create_table(
        "raw_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_type", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("object_storage_key", sa.String(length=800), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("is_deleted_at_source", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_sources.id"], name=op.f("fk_raw_snapshots_source_id_data_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_snapshots")),
        sa.UniqueConstraint(
            "source_id", "external_type", "external_id", "content_hash", name="raw_identity"
        ),
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_login", sa.String(length=200), nullable=False),
        sa.Column("repository_name", sa.String(length=300), nullable=False),
        sa.Column("full_name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("homepage", sa.String(length=800), nullable=True),
        sa.Column("primary_language", sa.String(length=100), nullable=True),
        sa.Column("license_spdx", sa.String(length=100), nullable=True),
        sa.Column("default_branch", sa.String(length=300), nullable=False),
        sa.Column("created_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["entities.id"], name=op.f("fk_repositories_id_entities")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("full_name", name=op.f("uq_repositories_full_name")),
        sa.UniqueConstraint(
            "github_repository_id", name=op.f("uq_repositories_github_repository_id")
        ),
    )
    op.create_table(
        "package_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("published_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.Column("license_expression", sa.String(length=300), nullable=True),
        sa.Column("repository_url_raw", sa.String(length=800), nullable=True),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_package_versions_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_package_versions_snapshot_id_raw_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_versions")),
        sa.UniqueConstraint("package_id", "version", name="package_version"),
    )
    op.create_table(
        "repository_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stars_count", sa.Integer(), nullable=False),
        sa.Column("forks_count", sa.Integer(), nullable=False),
        sa.Column("watchers_count", sa.Integer(), nullable=False),
        sa.Column("subscribers_count", sa.Integer(), nullable=True),
        sa.Column("open_items_count", sa.Integer(), nullable=False),
        sa.Column("pushed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_observations_repository_id_repositories"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_repository_observations_snapshot_id_raw_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_observations")),
        sa.UniqueConstraint("repository_id", "observed_at", name="repository_observed_at"),
    )
    op.create_table(
        "repository_work_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("github_item_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("author_association", sa.String(length=50), nullable=True),
        sa.Column("created_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_bot_likely", sa.Boolean(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_work_items_repository_id_repositories"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_repository_work_items_snapshot_id_raw_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_work_items")),
        sa.UniqueConstraint("repository_id", "github_item_id", name="repository_work_item"),
    )
    op.create_index(
        "ix_work_item_repository_type_state",
        "repository_work_items",
        ["repository_id", "item_type", "state"],
        unique=False,
    )
    op.create_table(
        "request_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_key", sa.String(length=100), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("etag", sa.String(length=300), nullable=True),
        sa.Column("rate_limit_limit", sa.Integer(), nullable=True),
        sa.Column("rate_limit_remaining", sa.Integer(), nullable=True),
        sa.Column("rate_limit_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_after_seconds", sa.Integer(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("error_class", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["ingestion_runs.id"], name=op.f("fk_request_records_run_id_ingestion_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_records")),
    )
    op.create_index(
        op.f("ix_request_records_request_fingerprint"),
        "request_records",
        ["request_fingerprint"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_records_request_fingerprint"), table_name="request_records")
    op.drop_table("request_records")
    op.drop_index("ix_work_item_repository_type_state", table_name="repository_work_items")
    op.drop_table("repository_work_items")
    op.drop_table("repository_observations")
    op.drop_table("package_versions")
    op.drop_table("repositories")
    op.drop_table("raw_snapshots")
    op.drop_table("packages")
    op.drop_table("ingestion_runs")
    op.drop_table("entity_external_ids")
    op.drop_table("entities")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
