"""add source policies and data quality events

Revision ID: dd596b496fe1
Revises: a42386ca9897
Create Date: 2026-07-29 21:29:32.026245
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dd596b496fe1"
down_revision: str | Sequence[str] | None = "a42386ca9897"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_policies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("commercial_use_status", sa.String(length=30), nullable=False),
        sa.Column("storage_permission", sa.String(length=30), nullable=False),
        sa.Column("derived_data_permission", sa.String(length=30), nullable=False),
        sa.Column("llm_processing_permission", sa.String(length=30), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=True),
        sa.Column("terms_url", sa.String(length=800), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_source_policies_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_policies")),
        sa.UniqueConstraint("source_id", "version", name="source_policy_version"),
    )
    op.create_table(
        "data_quality_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("external_type", sa.String(length=80), nullable=True),
        sa.Column("external_id", sa.String(length=300), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_data_quality_events_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_data_quality_events_snapshot_id_raw_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_data_quality_events_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_events")),
    )
    op.create_index(
        "ix_quality_event_run_type", "data_quality_events", ["run_id", "event_type"], unique=False
    )
    op.create_index(
        "ix_quality_event_source_observed",
        "data_quality_events",
        ["source_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_quality_event_source_observed", table_name="data_quality_events")
    op.drop_index("ix_quality_event_run_type", table_name="data_quality_events")
    op.drop_table("data_quality_events")
    op.drop_table("source_policies")
    # ### end Alembic commands ###
