"""add deterministic normalization pipeline

Revision ID: e806cadf10cf
Revises: 4aab642f84e7
Create Date: 2026-07-30 02:05:52.517662
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e806cadf10cf"
down_revision: str | Sequence[str] | None = "4aab642f84e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "normalization_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("normalizer_key", sa.String(length=80), nullable=False),
        sa.Column("normalizer_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_normalization_runs_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalization_runs")),
    )
    op.create_table(
        "normalized_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("normalization_run_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("normalizer_key", sa.String(length=80), nullable=False),
        sa.Column("normalizer_version", sa.String(length=80), nullable=False),
        sa.Column("document_type", sa.String(length=80), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("canonical_url", sa.String(length=800), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("normalized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_class", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_normalized_documents_entity_id_entities")
        ),
        sa.ForeignKeyConstraint(
            ["normalization_run_id"],
            ["normalization_runs.id"],
            name=op.f("fk_normalized_documents_normalization_run_id_normalization_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_normalized_documents_snapshot_id_raw_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_documents")),
        sa.UniqueConstraint(
            "snapshot_id",
            "normalizer_key",
            "normalizer_version",
            name="normalized_snapshot_version",
        ),
    )
    op.create_index(
        "ix_normalized_document_entity_type",
        "normalized_documents",
        ["entity_id", "document_type"],
        unique=False,
    )
    op.add_column("raw_snapshots", sa.Column("run_id", sa.Uuid(), nullable=True))
    op.add_column("raw_snapshots", sa.Column("collection_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_raw_snapshots_collection_id_ingestion_collections"),
        "raw_snapshots",
        "ingestion_collections",
        ["collection_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_raw_snapshots_run_id_ingestion_runs"),
        "raw_snapshots",
        "ingestion_runs",
        ["run_id"],
        ["id"],
    )
    op.add_column(
        "repository_observations",
        sa.Column("size", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("repository_observations", "size", server_default=None)
    op.add_column(
        "repository_observations",
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_unique_constraint(
        "repository_observation_snapshot", "repository_observations", ["snapshot_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("repository_observation_snapshot", "repository_observations", type_="unique")
    op.drop_column("repository_observations", "updated_at_source")
    op.drop_column("repository_observations", "size")
    op.drop_constraint(
        op.f("fk_raw_snapshots_run_id_ingestion_runs"), "raw_snapshots", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_raw_snapshots_collection_id_ingestion_collections"),
        "raw_snapshots",
        type_="foreignkey",
    )
    op.drop_column("raw_snapshots", "collection_id")
    op.drop_column("raw_snapshots", "run_id")
    op.drop_index("ix_normalized_document_entity_type", table_name="normalized_documents")
    op.drop_table("normalized_documents")
    op.drop_table("normalization_runs")
    # ### end Alembic commands ###
