"""track terminal incomplete collections

Revision ID: e926f2f86872
Revises: e806cadf10cf
Create Date: 2026-07-30 02:52:02.265136
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e926f2f86872"
down_revision: str | Sequence[str] | None = "e806cadf10cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for table_name in (
        "collection_pages",
        "ingestion_checkpoints",
        "ingestion_collections",
    ):
        op.add_column(
            table_name,
            sa.Column(
                "resume_available",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            ),
        )
        op.alter_column(table_name, "resume_available", server_default=None)
    op.add_column(
        "collection_pages",
        sa.Column("completeness_reason", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "ingestion_collections",
        sa.Column("completeness_reason", sa.String(length=80), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingestion_collections", "completeness_reason")
    op.drop_column("ingestion_collections", "resume_available")
    op.drop_column("ingestion_checkpoints", "resume_available")
    op.drop_column("collection_pages", "completeness_reason")
    op.drop_column("collection_pages", "resume_available")
    # ### end Alembic commands ###
